baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
themes = ["hugo-embed-pdf-shortcode"]
enableInLineShortcodes = true
cleanDestinationDir = true

[params]
    name = 'Hugo Onghai'

[caches]
  [caches.images]
    dir = ':cacheDir/images'